---
#
# This file contains configuration flags to customize your site
#
# Name of your site (displayed in the header)
title: "ENGL 460: The Blog"
# Short bio or description (displayed in the header)
description: The course blog for ENGL 460 at Texas A&M
semester: fall2020
author:
  name: Andrew Pilsch
  url: http://andrew.pilsch.com

show_downloads: false

#
# !! DON'T EDIT BELOW THIS MESSAGE
#
# Use the following plug-ins
plugins:
  - jekyll-sitemap  # Create a sitemap using the official Jekyll sitemap gem
  - jekyll-feed  # Create an Atom feed using the official Jekyll feed gem

# Exclude these files from your production _site
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME
